TeleTextWebApiServer/TeleTextWebApiClient/Models/APIDTOs/SuccessDTO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TeleTextWebApiServer.Models
{
    public class SuccessDTO
    {
        public int success { get; set; }
        public string[] message { get; set; }
    }
}

TeleTextWebApiServer/TeleTextWebApiClient/Controllers/TeleTextController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeleTextWebApiClient.Models.APIDTOs;

namespace TeleTextWebApiClient.Controllers
{
    public class TeleTextController : Controller
    {
        public ActionResult SendTeleText()
        {
            return View();
        }

        public ActionResult GetServerResults(string tbTeleText)
        {
            List<MessageEntity> messageResponse = getResponseFromTeleTextApi(tbTeleText);

            return View(messageResponse);
        }

        private List<MessageEntity> getResponseFromTeleTextApi(string inputText)
        {
            try
            {
                //string SAMPLE_TEXT =
                //"Please write a program that breaks this text into small chucks. Each chunk should have a maximum length of 25 " +
                //"characters. The program should try to break on complete sentences or punctuation marks if possible.  " +
                //"If a comma or sentence break occurs within 5 characters of the max line length, the line should be broken early.  " +
                //"The exception to this rule is when the next line will only contain 5 characters.  Redundant whitespace should " +
                //"not be counted between lines, and any duplicate   spaces should be removed.  " +
                //"Does this make sense? If not please ask for further clarification, an array containing " +
                //"the desired outcome has been provided below. Any text beyond this point is not part of the instructions, " +
                //"it's only here to ensure test converge. Finish line. Aaa asdf asdfjk las, asa.";
                
                using (var client = new WebClient())
                {
                    client.Headers[HttpRequestHeader.ContentType] = "application/x-www-form-urlencoded";
                    var data = "=" + inputText;
                    var result1 = client.UploadString("http://localhost:58592/api/teletext", "POST", data);

                    List<MessageEntity> messageResponse = JsonConvert.DeserializeObject<List<MessageEntity>>(result1);
                    return messageResponse;
                }
            }
            catch (Exception ex)
            {

                throw;
            }
        }
    }
}

TeleTextWebApiServer/TeleTextWebApiClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" 
xml:lang="en"  
lang="@System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TeleText Application", "", "TeleText", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My TeleText Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TeleTextWebApiServer/TeleTextWebApiClient/Views/TeleText/GetServerResults.cshtml
@model List<TeleTextWebApiClient.Models.APIDTOs.MessageEntity>

@{
    //ViewBag.Title = "GetServerResults";
}

<h1>GetServerResults</h1>
<h2>Result from TeleText WEB API</h2>
<ol>
    @foreach (var msg in Model)
    {
        <li>@msg.MessageLine</li>
    }
</ol>

TeleTextWebApiServer/TeleTextWebApiClient/Views/TeleText/SendTeleText.cshtml
@model TeleTextWebApiClient.Models.APIDTOs.MessageEntity

@{
    ViewBag.Title = "SendTeleText";
}

<h2>SendTeleText</h2>
<br />
@*<form action="GetServerResults" method="post">
    <textarea Name="tbTeleText" rows="10" cols="800">
            This TextBox will allow the user to enter multiple lines of text.  When the RETURN key is pressed,
            or when typed text reaches the edge of the text box, a new line is automatically inserted.
        </textarea>

    <input type="submit" value="Send" />
</form>*@

@using (Html.BeginForm("GetServerResults", "TeleText"))
{
    <textarea Name="tbTeleText" rows="10" cols="800">Please write a program that breaks this text into small chucks. Each chunk should have a maximum length of 25 characters. The program should try to break on complete sentences or punctuation marks if possible.  If a comma or sentence break occurs within 5 characters of the max line length, the line should be broken early.  The exception to this rule is when the next line will only contain 5 characters.  Redundant whitespace should not be counted between lines, and any duplicate   spaces should be removed.  Does this make sense? If not please ask for further clarification, an array containing the desired outcome has been provided below. Any text beyond this point is not part of the instructions, it's only here to ensure test converge. Finish line. Aaa asdf asdfjk las, asa.
        </textarea>
        <br />
    <input type="submit" value="Send" />
}